openapi: 3.0.1
info:
  title: My App API
  description: My App API description
  version: "1.0"
paths:
  /:
    get:
      summary: Health Check Endpoints
      operationId: up
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: string
  /users/register:
    post:
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
        required: true
      responses:
        "200":
          description: Success
  /users/all:
    get:
      operationId: all
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /users/login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        password:
          type: string
    RegisterUserRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string
        email:
          type: string

